made more adjustments for sudo loading and struct testing loading inside sshswitchkey

diff --git a/sshswitchkey b/sshswitchkey
--- a/sshswitchkey
+++ b/sshswitchkey
@@ -47,7 +47,7 @@ else
     IFS=''                 # to read line by line and keep space
     IFS= read -r ONEPIPE   # to avoid interpretation of backslashes.
     PIPED="${ONEPIPE}"
-        [ ! -z "$PIPED" ] && COUNTER=$((COUNTER+1))
+        [ -n "$PIPED" ] && COUNTER=$((COUNTER+1))
 
     while read ONEPIPE
     do
@@ -66,7 +66,7 @@ ${ONEPIPE}"
     IFS=$OLDIFS
 fi
 # Piped Input
-#if [ ! -z "$PIPED" ]
+#if [ -n "$PIPED" ]
 # then
 # echo "this is pipe..die "
 # exit 0;
@@ -107,7 +107,7 @@ THISSCRIPTNAME=`basename "$0"`
 FILENAME=""
 VERBOSE=""
 # Yes argument, not piped
-if [ ! -z "$1" ] && [ -z "$PIPED" ]
+if [ -n "$1" ] && [ -z "$PIPED" ]
   then
   {
     if [[ "$1" == "-v" ]] ;
@@ -119,7 +119,7 @@ if [ ! -z "$1" ] && [ -z "$PIPED" ]
   }
 fi
 # Yes argument, yes piped
-if [ ! -z "$1" ] && [ ! -z "$PIPED" ]
+if [ -n "$1" ] && [ -n "$PIPED" ]
   then
   {
     if [[ "$1" == "-v" ]] ;
@@ -131,7 +131,7 @@ if [ ! -z "$1" ] && [ ! -z "$PIPED" ]
 fi
 
 # Not argument, yes piped
-if [ -z "$1" ] && [ ! -z "$PIPED" ]
+if [ -z "$1" ] && [ -n "$PIPED" ]
   then
   {
     FILENAME="${PIPED}";
@@ -157,7 +157,7 @@ if [ -z "$1" ] && [ -z "$PIPED" ]
 fi
 
 # Yes argument, not piped
-if [ ! -z "$2" ]
+if [ -n "$2" ]
   then
   {
     if [[ "$2" == "-v" ]] ;
@@ -176,7 +176,7 @@ fi
     while read -r ONE_FILENAME; do
       # if not empty
       PERMISIONS=""
-      if [ ! -z "${ONE_FILENAME}" ] ; then
+      if [ -n "${ONE_FILENAME}" ] ; then
         PERMISIONS=$(stat -f "%OLp" "${ONE_FILENAME}")
       fi
       if [[ "${VERBOSE}" == "ON" ]] ;
@@ -196,7 +196,7 @@ fi
     while read -r ONE_FILENAME; do
       # if not empty
       PERMISIONS=""
-      if [ ! -z "${ONE_FILENAME}" ] ; then
+      if [ -n "${ONE_FILENAME}" ] ; then
         PERMISIONS=$(stat --format '%a' "${ONE_FILENAME}")
       fi
       if [[ "${VERBOSE}" == "ON" ]] ;
@@ -235,77 +235,80 @@ fi
 # 39:  SIMPLE helloworld echo -e "\033[38;5;39m FOREGROUND   "; echo -e "\033[48;5;39m BACKGROUND   "
 # 45:  SIMPLE helloworld echo -e "\033[38;5;45m FOREGROUND   "; echo -e "\033[48;5;45m BACKGROUND   "
 
+  load_struct_testing_wget() {
+      local provider="$HOME/_/clis/execute_command_intuivo_cli/struct_testing"
+      [[   -e "${provider}"  ]] && source "${provider}" && echo  "Loaded locally"
+      [[ ! -e "${provider}"  ]] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
+      ( ( ! command -v passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
+      return 0
+  } # end load_struct_testing_wget
 
-
-echo -en "${RESET}\033[38;5;246m" 2>&1
-
-
-# -- SUDO START
-if [[ "${USER}" == 'root' || "${LOGNAME}" == 'root' ]] ; then
+if [ -z "$PIPED" ] ; then
 {
-  if [[ -n "${SUDO_USER}" && "${SUDO_USER}" != 'root' ]] ; then
+  echo -en "${RESET}\033[38;5;246m" 2>&1
+
+
+  # -- SUDO START
+  if [[ "${USER}" == 'root' || "${LOGNAME}" == 'root' ]] ; then
   {
-    echo -e "\033[38;5;20m Suddoed-in from ${SUDO_USER} ! "
+    if [[ -n "${SUDO_USER}" && "${SUDO_USER}" != 'root' ]] ; then
+    {
+      echo -e "\033[38;5;20m Suddoed-in from ${SUDO_USER} ! "
+    }
+    else
+    {
+      echo -e "\033[38;5;18m Error"
+      echo " "
+      echo -e "\033[38;5;19m  Must run this as a 'USER' not from root "
+      echo " "
+      echo -e "\033[38;5;20m  expected be run by a user with SUDO rights "
+      exit 1
+    }
+    fi
+  }
+  fi
+  if  ( env | grep "SUDO_USER"  &>/dev/null  ) || [[ -z "${SUDO_USER}" ]] ; then
+  {
+
+    sudo echo -n "Hey! sudo "
+    echo -e "\033[38;0m "
+    # USER=root
+    # SHELL=/bin/sh
+    # SUDO_COMMAND=/usr/bin/env
+    # SUDO_USER=zeus
+    # SUDO_UID=501
+    # SUDO_GID=20
+    # echo UID=$(sudo id -u $(logname))
+    SUDO_USER="${USER}"
+    SUDO_UID="${UID}"
+    LOGNAME="root"
+    USER="root"
+    sudo env | grep SUDO
+    sudo env | grep LOGNAME
+    sudo env | grep USER
+    sudo env | grep UID
+    echo -e "Suddoed in from ${SUDO_USER} "
   }
   else
   {
     echo -e "\033[38;5;18m Error"
     echo " "
-    echo -e "\033[38;5;19m  Must run this as a 'USER' not from root "
+    echo -e "\033[38;5;19m  SUDO_USER exists! from some weird reason but is not root"
     echo " "
-    echo -e "\033[38;5;20m  expected be run by a user with SUDO rights "
+    echo -e "\033[38;5;20m  this is strange. I cannot proceed like this. "
     exit 1
   }
   fi
-}
-fi
-if  ( env | grep "SUDO_USER"  &>/dev/null  ) || [[ -z "${SUDO_USER}" ]] ; then
-{
-
-  sudo echo -n "Hey! sudo "
-  echo -e "\033[38;0m "
-  # USER=root
-  # SHELL=/bin/sh
-  # SUDO_COMMAND=/usr/bin/env
-  # SUDO_USER=zeus
-  # SUDO_UID=501
-  # SUDO_GID=20
-  # echo UID=$(sudo id -u $(logname))
-  SUDO_USER="${USER}"
-  SUDO_UID="${UID}"
-  LOGNAME="root"
-  USER="root"
-  sudo env | grep SUDO
-  sudo env | grep LOGNAME
-  sudo env | grep USER
-  sudo env | grep UID
-  echo -e "Suddoed in from ${SUDO_USER} "
+  SUDOS="$(sudo env | grep SUDO_USER)"
+  load_struct_testing_wget
+  USER_HOME="${HOME}"
 }
 else
 {
-  echo -e "\033[38;5;18m Error"
-  echo " "
-  echo -e "\033[38;5;19m  SUDO_USER exists! from some weird reason but is not root"
-  echo " "
-  echo -e "\033[38;5;20m  this is strange. I cannot proceed like this. "
-  exit 1
+  load_struct_testing_wget
 }
 fi
 
-
-
-SUDOS="$(sudo env | grep SUDO_USER)"
-
-load_struct_testing_wget() {
-    local provider="$HOME/_/clis/execute_command_intuivo_cli/struct_testing"
-    [[   -e "${provider}"  ]] && source "${provider}" && echo  "Loaded locally"
-    [[ ! -e "${provider}"  ]] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
-    ( ( ! command -v passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
-    return 0
-} # end load_struct_testing_wget
-load_struct_testing_wget
-
-USER_HOME="${HOME}"
 enforce_variable_with_value USER_HOME "${USER_HOME}"
 
 # USER=root
