added fix for strings and sudo solution less complicated to ssh swtiching

diff --git a/sshswitchkey b/sshswitchkey
--- a/sshswitchkey
+++ b/sshswitchkey
@@ -1,20 +1,8 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # @author Zeus Intuivo <zeus@intuivo.com>
 #
 #
-
-
-load_struct_testing_wget(){
-    local provider="$HOME/_/clis/execute_command_intuivo_cli/struct_testing"
-    [   -e "${provider}"  ] && source "${provider}" && echo  "Loaded locally"
-    [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
-    ( ( ! command -v passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
-} # end load_struct_testing_wget
-load_struct_testing_wget
-
-USER_HOME=$HOME
-enforce_variable_with_value USER_HOME "$USER_HOME"
 
 # 18:  SIMPLE helloworld echo -e "\033[38;5;18m FOREGROUND   "; echo -e "\033[48;5;18m BACKGROUND   "
 # 19:  SIMPLE helloworld echo -e "\033[38;5;19m FOREGROUND   "; echo -e "\033[48;5;19m BACKGROUND   "
@@ -29,13 +17,94 @@ enforce_variable_with_value USER_HOME "$USER_HOME"
 # 39:  SIMPLE helloworld echo -e "\033[38;5;39m FOREGROUND   "; echo -e "\033[48;5;39m BACKGROUND   "
 # 45:  SIMPLE helloworld echo -e "\033[38;5;45m FOREGROUND   "; echo -e "\033[48;5;45m BACKGROUND   "
 echo -en "${RESET}\033[38;5;246m" 2>&1
-(( DEBUG )) && sudo echo "Hey!"
+
+
+if [[ "${USER}" == 'root' || "${LOGNAME}" == 'root' ]] ; then
+{
+  if [[ -n "${SUDO_USER}" && "${SUDO_USER}" != 'root' ]] ; then
+  {
+    echo -e "\033[38;5;20m Suddoed-in from ${SUDO_USER} ! "
+  }
+  else
+  {
+    echo -e "\033[38;5;18m Error"
+    echo " "
+    echo -e "\033[38;5;19m  Must run this as a 'USER' not from root "
+    echo " "
+    echo -e "\033[38;5;20m  expected be run by a user with SUDO rights "
+    exit 1
+  }
+  fi
+}
+fi
+if  ( env | grep "SUDO_USER"  &>/dev/null  ) || [[ -z "${SUDO_USER}" ]] ; then
+{
+
+  sudo echo -n "Hey! sudo "
+  echo -e "\033[38;0m "
+  # USER=root
+  # SHELL=/bin/sh
+  # SUDO_COMMAND=/usr/bin/env
+  # SUDO_USER=zeus
+  # SUDO_UID=501
+  # SUDO_GID=20
+  # echo UID=$(sudo id -u $(logname))
+  SUDO_USER="${USER}"
+  SUDO_UID="${UID}"
+  LOGNAME="root"
+  USER="root"
+  sudo env | grep SUDO
+  sudo env | grep LOGNAME
+  sudo env | grep USER
+  sudo env | grep UID
+  echo -e "Suddoed in from ${SUDO_USER} "
+}
+else
+{
+  echo -e "\033[38;5;18m Error"
+  echo " "
+  echo -e "\033[38;5;19m  SUDO_USER exists! from some weird reason but is not root"
+  echo " "
+  echo -e "\033[38;5;20m  this is strange. I cannot proceed like this. "
+  exit 1
+}
+fi
+
+
+
+SUDOS="$(sudo env | grep SUDO_USER)"
+
+load_struct_testing_wget() {
+    local provider="$HOME/_/clis/execute_command_intuivo_cli/struct_testing"
+    [[   -e "${provider}"  ]] && source "${provider}" && echo  "Loaded locally"
+    [[ ! -e "${provider}"  ]] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
+    ( ( ! command -v passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
+    return 0
+} # end load_struct_testing_wget
+load_struct_testing_wget
+
+USER_HOME="${HOME}"
+enforce_variable_with_value USER_HOME "${USER_HOME}"
+
+# USER=root
+# SHELL=/bin/sh
+# SUDO_COMMAND=/usr/bin/env
+# SUDO_USER=zeus
+# SUDO_UID=501
+# SUDO_GID=20
+enforce_variable_with_value USER "${USER}"
+enforce_variable_with_value SHELL "${SHELL}"
+enforce_variable_with_value LOGNAME "${LOGNAME}"
+enforce_variable_with_value SUDO_USER "${SUDO_USER}"
+enforce_variable_with_value SUDO_UID "${SUDO_UID}"
+# enforce_variable_with_value SUDO_GID "${SUDO_GID}"
+
 # echo -e "\033[38;5;45m FOREGROUND   "; echo -e "\033[48;5;45m BACKGROUND   "
 # cd ${USER_HOME}/
 EXECUTEOWD=$(pwd)
-(( DEBUG )) && echo $EXECUTEOWD
-[ -f "$EXECUTEOWD/.temp_keys" ] && (( DEBUG )) &&  echo "I found it "
-[ -f "$EXECUTEOWD/.temp_keys" ] &&  . "$EXECUTEOWD/.temp_keys"
+(( DEBUG )) && echo "${EXECUTEOWD}"
+[[ -f "${EXECUTEOWD}/.temp_keys" ]] && (( DEBUG )) &&  echo "I found it "
+[[ -f "${EXECUTEOWD}/.temp_keys" ]] &&  . "${EXECUTEOWD}/.temp_keys"
 
 
 if [[ -n "${VPNREQUIRED}" ]] ;  then
@@ -72,19 +141,23 @@ fi
 
 
 (( DEBUG )) && echo -e "\033[38;5;20m"  2>&1
-cd ${USER_HOME}/.ssh/
+cd "${USER_HOME}/.ssh/"
 #mkdir -p ${USER_HOME}/.ssh/
-sudo chmod 700 ${USER_HOME}/.ssh/
+sudo chmod 700 "${USER_HOME}/.ssh/"
+sudo chown -R "${SUDO_USER}" "${USER_HOME}/.ssh/"
 
-[ ! -d ${USER_HOME}/.ssh/ ] && echo -e "\033[38;5;19m\n  Error ${USER_HOME}/.ssh/ does not exist \n "
+[[ ! -d "${USER_HOME}/.ssh/" ]] && echo -e "\033[38;5;19m\n  Error ${USER_HOME}/.ssh/ does not exist \n "
 KEYLIST=$(ls *.pub | sed 's/id_rsa.pub//' | sed 's/_rsa.pub//')
 enforce_variable_with_value KEYLIST $KEYLIST
 
 
 PROVIDED_USER=""
 if [[  -n "${1}" ]] ;  then
-    PROVIDED_USER="${1}"
+{
+  PROVIDED_USER="${1}"
+}
 else
+{
 	echo -e "\033[38;5;18m Error"
 	echo " "
 	echo -e "\033[38;5;19m  ssh_generatekeys username    "
@@ -92,8 +165,9 @@ else
 	echo -e "\033[38;5;20m  expected"
 	echo -e "\033[38;5;21m \n Pick from key on the list: \n ${KEYLIST} \n"
 	echo " "
-	enforce_variable_with_value PROVIDED_USER $PROVIDED_USER
+	enforce_variable_with_value PROVIDED_USER "${PROVIDED_USER}"
 	exit 1
+}
 fi
 
 
@@ -101,14 +175,26 @@ fi
 
 
 
-OUTPUT_FOLDER=$(pwd)
+OUTPUT_FOLDER="$(pwd)"
 (( DEBUG )) && echo -e "\033[38;5;25m" 2>&1
-[ ! -f "${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa" ] && echo -e "\n  Error this key does not exist. Pick from key on the list: \n ${KEYLIST} \n" && exit 1
-sudo cp "${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa" "${OUTPUT_FOLDER}/id_rsa"
+[[ ! -f "${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa" ]] && echo -e "\n  Error this key does not exist. Pick from key on the list: \n ${KEYLIST} \n" && exit 1
+sudo chmod 700 "${OUTPUT_FOLDER}/id_rsa.pub"
+sudo chmod 700 "${OUTPUT_FOLDER}/id_rsa"
+sudo chown -R "${SUDO_USER}" "${OUTPUT_FOLDER}/id_rsa.pub"
+sudo chown -R "${SUDO_USER}" "${OUTPUT_FOLDER}/id_rsa"
+
+sudo chmod 700 "${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa.pub"
+sudo chmod 700 "${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa"
+sudo chown -R "${SUDO_USER}" "${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa.pub"
+sudo chown -R "${SUDO_USER}" "${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa"
+
 sudo cp "${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa.pub" "${OUTPUT_FOLDER}/id_rsa.pub"
+sudo cp "${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa" "${OUTPUT_FOLDER}/id_rsa"
 
 sudo chmod 700 "${OUTPUT_FOLDER}/id_rsa.pub"
 sudo chmod 700 "${OUTPUT_FOLDER}/id_rsa"
+sudo chown -R "${SUDO_USER}" "${OUTPUT_FOLDER}/id_rsa.pub"
+sudo chown -R "${SUDO_USER}" "${OUTPUT_FOLDER}/id_rsa"
 
 (( DEBUG )) && echo chmod 1 get_file_chmod "${OUTPUT_FOLDER}"
 get_file_chmod "${OUTPUT_FOLDER}"  &>/dev/null
@@ -123,21 +209,30 @@ get_file_chmod "${OUTPUT_FOLDER}/id_rsa.pub"  &>/dev/null
 (( DEBUG )) && sudo cat "${OUTPUT_FOLDER}/id_rsa.pub"
 # REF: https://www.shellhacks.com/regex-find-email-addresses-file-grep/
 GET_EMAIL_FROM_PUB_KEY=$(sudo cat "${OUTPUT_FOLDER}/id_rsa.pub" | grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b")
-enforce_variable_with_value GET_EMAIL_FROM_PUB_KEY $GET_EMAIL_FROM_PUB_KEY
+enforce_variable_with_value GET_EMAIL_FROM_PUB_KEY "${GET_EMAIL_FROM_PUB_KEY}"
 
 GET_USERNAME_FROM_EMAIL=$(echo "${GET_EMAIL_FROM_PUB_KEY}" | grep -E -o "\b[A-Za-z0-9._%+-]+\b" | head -1 )
-enforce_variable_with_value GET_USERNAME_FROM_EMAIL $GET_USERNAME_FROM_EMAIL
+enforce_variable_with_value GET_USERNAME_FROM_EMAIL "${GET_USERNAME_FROM_EMAIL}"
 
 USERNAME="${GET_USERNAME_FROM_EMAIL}"
-enforce_variable_with_value USERNAME $USERNAME
+enforce_variable_with_value USERNAME "${USERNAME}"
 (( DEBUG )) && echo -e "\033[38;5;26m" 2>&1
-(( DEBUG )) && echo "$USERNAME";
+(( DEBUG )) && echo "${USERNAME}";
 #ssh -vT git@github.com
 sudo chmod 400 "${OUTPUT_FOLDER}/id_rsa.pub"
 sudo chmod 400 "${OUTPUT_FOLDER}/id_rsa"
+# Assuming USER is root with sudo
+sudo chown -R "${SUDO_USER}" "${OUTPUT_FOLDER}/id_rsa.pub"
+sudo chown -R "${SUDO_USER}" "${OUTPUT_FOLDER}/id_rsa"
+
+sudo chmod 400 "${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa.pub"
+sudo chmod 400 "${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa"
+# Assuming USER is root with sudo
+sudo chown -R "${USER}" "${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa.pub"
+sudo chown -R "${USER}" "${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa"
 
 
-(( DEBUG )) && enforce_variable_with_value GITPROVIDER $GITPROVIDER
+(( DEBUG )) && enforce_variable_with_value GITPROVIDER "${GITPROVIDER}"
           if ( typeset -p "GITPROVIDER"  &>/dev/null ) &&  [ -n "${GITPROVIDER+x}" ] ; then
           {
             (( DEBUG )) && echo -e "${LIGHTGREEN} ✔ ${LIGHTYELLOW} ${GITPROVIDER} is given "
@@ -197,6 +292,7 @@ sudo chmod 400 "${OUTPUT_FOLDER}/id_rsa"
 
 	# check operation systems
 	if [[ "$(uname)" == "Darwin" ]] ; then
+  {
 	  # Do something under Mac OS X platform
 	  (( DEBUG )) && echo -e "\033[38;5;26m Stopping All SSH. It is expected to restart."
 	  (( DEBUG )) && echo -e "\033[38;5;27m"
@@ -210,20 +306,25 @@ sudo chmod 400 "${OUTPUT_FOLDER}/id_rsa"
 	  wait
 	  (( DEBUG )) && echo -e "\033[38;5;33m"
 	  (( DEBUG )) && echo "Adding just the only key we want to use."
-	  sudo ssh-add -K ${OUTPUT_FOLDER}/id_rsa
+	  sudo ssh-add -K "${OUTPUT_FOLDER}/id_rsa"
 
      (( FLAGGITPROVIDER )) &&  [[ "${TEST_GIT}" ==  *"Permission denied"* ]] && $(pbcopy < ${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa.pub)  && echo "------ Key Needs to be added in WebPAGE. Copied to CLipboard"
+  }
 	elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]] ; then
+  {
 	  # Do something under GNU/Linux platform
 	  # ubuntu lsb_release -i | sed 's/Distributor\ ID://g' = \tUbuntu\n
     #  (( FLAGGITPROVIDER )) &&  [[ "${TEST_GIT}" ==  *"Permission denied"* ]] && $(xclip -sel clip < ${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa.pub)  && echo "------ Key Needs to be added in WebPAGE. Copied to CLipboard"
      (( FLAGGITPROVIDER )) &&  echo "no xclip"
+  }
 	elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]] ; then
+  {
 	  # Do something under Windows NT platform
      (( FLAGGITPROVIDER )) &&  [[ "${TEST_GIT}" ==  *"Permission denied"* ]] && $(cat ${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa.pub | cpy)  && echo "------ Key Needs to be added in WebPAGE. Copied to CLipboard"
 	  # cat ${OUTPUT_FOLDER}/${PROVIDED_USER}_rsa.pub | cpy
 	  # cat ${USER_HOME}/.ssh/id_rsa.pub | clip
 	  # nothing here
+  }
 	fi
 
 if  (( FLAGGITPROVIDER )) &&  [[ "${TEST_GIT}" ==  *"successfully authenticated"* ]] ; then
@@ -231,7 +332,7 @@ if  (( FLAGGITPROVIDER )) &&  [[ "${TEST_GIT}" ==  *"successfully authenticated"
   GET_USERNAME_FROM_GREETING=$(echo "${TEST_GIT%\!*}" | sed -e 's/Hi //')
   enforce_variable_with_value GET_USERNAME_FROM_GREETING $GET_USERNAME_FROM_GREETING
   USERNAME="${GET_USERNAME_FROM_GREETING}"
-  enforce_variable_with_value USERNAME $USERNAME
+  enforce_variable_with_value USERNAME "${USERNAME}"
 }
 fi
 
@@ -240,7 +341,7 @@ git config --global user.email "${GET_EMAIL_FROM_PUB_KEY}"
 echo -en "\033[38;5;45m" 2>&1
 git config --global user.name "${USERNAME}"
 echo -en "\033[38;5;51m" 2>&1
-OUTPUT_GITCONFIG=$(git config --global -l )
+OUTPUT_GITCONFIG="$(git config --global -l )"
 echo -n "$OUTPUT_GITCONFIG" | grep "user."
 (( DEBUG )) && sudo ssh-add -l
 echo -en "\033[0m" 2>&1
